// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TercumanTakipWeb.Models;

#nullable disable

namespace TercumanTakipWeb.Migrations
{
    [DbContext(typeof(TercumanTakipDbContext))]
    partial class TercumanTakipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TercumanTakipWeb.Models.DilListesi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Dil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("DilListesi");
                });

            modelBuilder.Entity("TercumanTakipWeb.Models.OfisListesi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("OfisAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("OfisListesi");
                });

            modelBuilder.Entity("TercumanTakipWeb.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parola")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seviye")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TercumanTakipWeb.Models.isTakipListesi_DisGorev", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("DanisanAdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("DonusSaati")
                        .HasColumnType("time");

                    b.Property<string>("DosyaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkBilgi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("GidisSaati")
                        .HasColumnType("time");

                    b.Property<DateOnly>("GidisTarihi")
                        .HasColumnType("date");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KurumHastaneAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YonlendirenKisi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("isTakipListesi_DisGorev");
                });

            modelBuilder.Entity("TercumanTakipWeb.Models.isTakipListesi_MigrantTV", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CeviriKonusu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CeviriTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Dil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkBilgi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KelimeSayisi")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeslendirmeSayisi")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("isTakipListesi_MigrantTV");
                });

            modelBuilder.Entity("TercumanTakipWeb.Models.isTakipListesi_Telefon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<DateOnly>("DestekTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Dil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosyaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkBilgi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GorusmeSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfisListesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TalepKisi_Birim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("isTakipListesi_Telefon");
                });

            modelBuilder.Entity("TercumanTakipWeb.Models.isTakipListesi_TopluArama", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AramaBasligi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AramaSayisi")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DestekTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Dil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkBilgi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfisListesi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("isTakipListesi_TopluArama");
                });

            modelBuilder.Entity("TercumanTakipWeb.Models.isTakipListesi_YaziliCeviri", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CeviriKonusu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CeviriTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Dil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkBilgi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KelimeSayisi")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("isTakipListesi_YaziliCeviri");
                });

            modelBuilder.Entity("TercumanTakipWeb.Models.isTakipListesi_Yuzyuze", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<DateOnly>("DestekTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Dil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosyaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkBilgi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GorusmeSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfisListesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TalepKisi_Birim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("isTakipListesi_Yuzyuze");
                });
#pragma warning restore 612, 618
        }
    }
}
